name: Issue Creation Handler

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  process-issue-creation-auto-comment:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Comment on issue creation
      uses: actions/github-script@v6
      with:
        script: |
          const eventType = context.payload.action;
          const issueNumber = context.issue.number;
          const actor = context.actor;
          const comment = `Hey @${actor}, Welcome to Github Actions Practice! 🎊
                           Thanks for opening issue #${issueNumber} ! 🙌 Please wait for the issue to be assigned. Happy Coding!! ✨`

          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            body: comment
          });
  

  process-issue-creation-add-label:
    runs-on: ubuntu-latest
    needs: comment-on-issue

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add label on issue creation
      uses: actions/github-script@v6
      with:
        script: |
          const issueNumber = context.issue.number;

          await github.rest.issues.addLabels({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issueNumber,
            labels: ['un assigned']
          });
          